const GET_USER_DETAILS = "GET_USER_DETAILS";
const GET_USER_DETAILS_ERROR = "GET_USER_DETAILS_ERROR";
const USER_DETAILS_ERROR_RESOLVED = "USER_DETAILS_ERROR_RESOLVED";
const STORE_USERNAME = "STORE_USERNAME";

export {
  STORE_USERNAME,
  GET_USER_DETAILS,
  USER_DETAILS_ERROR_RESOLVED,
  GET_USER_DETAILS_ERROR,
};
